name: pre-commit

on:
  pull_request:
    branches:
      - "**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all tags and branches

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - run: uvx pre-commit run --show-diff-on-failure --from-ref origin/${{ github.event.pull_request.base.ref }} --to-ref HEAD --show-diff-on-failure
        shell: bash

      - uses: reviewdog/action-typos@v1 # Chek fro typoss
